---
abstract: 'Convenience perl wrapper around IADsNameTranslate interface'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-NameTranslate
requires:
  Exporter: 0
  Win32::OLE: 0
  constant: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/win32-nametranslate
  repository: https://github.com/bingos/win32-nametranslate.git
version: 0.02
